name: Mevzuat API for Lovable

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  save-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Call API & Save
        run: |
          mkdir -p public
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"query": "güncel mevzuat", "page_size": 10}' \
            https://mevzuat-mcp-2z26.onrender.com/webhook/search \
            > public/mevzuat-data.json
            
      - name: Commit Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/mevzuat-data.json
          git commit -m "Update mevzuat data: $(date)" || exit 0
          git push
